export default {
    // error
    API_ERROR: 'API_ERROR',
    // auth
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILED: 'AUTH_FAILED',
    // posts list
    POSTS_LIST_RETRIEVED: 'POSTS_LIST_RETRIEVED',
    POST_CREATED: 'POST_CREATED',
    POST_DELETED: 'POST_DELETED',
    // post selection
    POST_SELECTION_SET_POST_ID: 'POST_SELECTION_SET_POST_ID',
    POST_SELECTION_POST_RETRIVED: 'POST_SELECTION_POST_RETRIVED',
    POST_SELECTION_COMPARABLE_POSTS_QUERY_RESULTS: 'POST_SELECTION_COMPARABLE_POSTS_QUERY_RESULTS',
    POST_SELECTION_SET_SELECTED_COMPARABLE_POSTS: 'POST_SELECTION_SET_SELECTED_COMPARABLE_POSTS',
    POST_SELECTION_LIKED: 'POST_SELECTION_LIKED'
};
